services:
  mongodb:
    build: ./mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
      MONGO_DB: ${MONGO_DB}
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  app1:
    build: ./app
    environment:
      APP_INSTANCE_NAME: app1
      MONGO_DB: ${MONGO_DB}
      APP_PORT: 3000
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      BACKUP_DIR: /app/backups
    volumes:
      - ./backups:/app/backups:z
    depends_on:
      mongodb:
        condition: service_healthy

  app2:
    build: ./app
    environment:
      APP_INSTANCE_NAME: app2
      MONGO_DB: ${MONGO_DB}
      APP_PORT: 3000
      APP_DB_USERNAME: ${APP_DB_USERNAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      BACKUP_DIR: /app/backups
    volumes:
      - ./backups:/app/backups:z
    depends_on:
      mongodb:
        condition: service_healthy

  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

volumes:
  mongo-data:
